Repository OpenSourceCommerce/log-explorer, pull requests merged in 2021-01, with the labels that each got.

#103 hot fix/LE-102
  assets/js/_config.js
  assets/js/actions/_event.js
  src/Constant/ErrorCodeConstant.php
  src/EventSubscriber/ExceptionsSubscriber.php
  src/Security/LoginFormAuthenticator.php
  tests/Feature/Api/DatabaseControllerTest.php
  tests/Feature/Api/GraphControllerTest.php
  tests/Feature/Api/UserControllerTest.php
Labels: bug

#106 Feature/le 105
  phpunit.xml.dist
  src/Controller/Api/StreamController.php
  src/Services/Stream/StreamService.php
Labels: enhancement

#111 LE-107 Can't access the page in middle of home page table #107
  assets/js/components/_js-grid-table.js
  assets/styles/component/_js-grid-table.scss
Labels: Code review
